name: go build && Docker Build and Push
on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        default: ohdat123
        type: string
      VERSION:
        type: string
        default: v0.1.${{ github.run_number }}
      DOCKERHUB_REPO:
        type: string
        default: ohdat
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      GIT_TOKEN:
        required: false
    outputs:
      image:
        description: "The image of docker build tag"
        value: ${{ jobs.build.outputs.image }}
      version:
        value: ${{ inputs.VERSION }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TAG: ${{ inputs.DOCKERHUB_REPO }}/${{ github.event.repository.name }}:${{ inputs.VERSION }}
      LATEST_TAG: ${{ inputs.DOCKERHUB_REPO }}/${{ github.event.repository.name }}:latest
    outputs:
      image: ${{ env.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
      - name: set GOPRIVATE
        run: |
          go env -w GOPRIVATE=github.com/ohdat
          git config --global url."https://${{ secrets.GIT_TOKEN || github.token }}@github.com".insteadOf "https://github.com"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --snapshot
      - run: mv dist/gomain_linux_amd64_v1 dist/gomain_linux_amd64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # cache-from: type=registry,ref=${{ env.LATEST_TAG }}
          # cache-to: type=inline
          tags: ${{ env.TAG }}
          # tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ inputs.VERSION  }}
          target_commitish: ${{ github.ref_name }}
