name: node build && Docker Build and Push
on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        default: ohdat123
        type: string
      VERSION:
        type: string
        default: v0.1.${{ github.run_number }}
      NODE_VERSION:
        default: "18"
        type: string
      BUILD_COMMANDS:
        default: "npm run build"
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      GIT_TOKEN:
        required: false
    outputs:
      image:
        description: "The image of docker build tag"
        value: ${{ jobs.build.outputs.image }}
      version:
        value: ${{ inputs.VERSION }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TAG: ${{ inputs.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ inputs.VERSION }}
      LATEST_TAG: ${{ inputs.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
    outputs:
      image: ${{ env.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4
      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
      - name: private npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GIT_TOKEN || github.token}}" > ~/.npmrc
      - run: npm install
      - name: run build
        run: ${{ inputs.BUILD_COMMANDS }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
          build-args: |
            GIT_TOKEN=${{ secrets.GIT_TOKEN || github.token }}
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ inputs.VERSION  }}
          target_commitish: ${{ github.ref_name }}
