name: Golnag CI
on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        default: ohdat123
        type: string
      NODE_VERSION:
        default: '14'
        type: string
      NODE_COMMANDS:
        default: ''
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      GIT_USER:
        required: true
      GIT_TOKEN:
        required: true
    outputs:
      image:
        description: 'The image of docker build tag'
        value: ${{ jobs.buildAndPush.outputs.image }}
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ inputs.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:1.1.${{ github.run_number }}
      LATEST_TAG: ${{ inputs.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
    outputs:
      image: ${{ env.TAG }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          #yarn install
          #yarn build:dev
           echo "//npm.pkg.github.com/:_authToken=${{secrets.GIT_TOKEN}}" > ~/.npmrc
           npm install
           ${{ inputs.NODE_COMMANDS }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}
